BridgedNetwork implementation
Code-Hex/vz pull request #151
Opened 2023-12-05 11:21 UTC by Raikerian

## Which issue(s) this PR fixes:

Found one issue related to that https://github.com/Code-Hex/vz/issues/138

## Additional documentation

Added implementation for BridgedNetwork in order to be able to create network device using bridge network, rather than NAT.
Using BridgedNetwork does indeed require special entitlements from Apple, which is a whole PIA to setup and test by itself, as you need proper certificates and signing in place after you got it added to your Organization by Apple. My current project does have those entitlements and needs bridged network, so I was able to test this and it does the job. Please let me know your thoughts if anything needs to be improved.

2023-12-09 11:41 UTC, Code-Hex requested changes

2023-12-09 11:41 UTC, Code-Hex commented on virtualization_11.m
> +    }
Please fix to return `const char *`

2023-12-09 11:41 UTC, Code-Hex commented on virtualization_11.m
> +    }
Please fix to return `const char *`

2023-12-09 11:41 UTC, Code-Hex commented on internal/objc/objc.go
> +}
These function definitions are not necessary.

2023-12-09 11:41 UTC, Code-Hex commented on network.go
> +func (b *baseBridgedNetwork) LocalizedDisplayName() string {
Could you add a GoDoc?

2023-12-20 11:50 UTC, Raikerian commented
@Code-Hex apologies for the delay, all the comments are now addressed

2023-12-20 15:01 UTC, Code-Hex approved these changes
Thanks

2023-12-20 15:02 UTC, merged

2023-12-20 15:02 UTC, Code-Hex commented
I will release tomorrow in JST